### PR TITLE
add example dag on project init

### LINKED ISSUE #4: init command should create a “hello world” DAG in CLI

### PR DESCRIPTION
**Pull request by andscoop**
- closes #4

### CODE REVIEW

**Comment by schnie** [comment]
@andscoop what you think about breaking these files out into their own?

**Comment by andscoop** [comment]
We can - I thought above moving them to `include/`

**Comment by schnie** [comment]
Sounds good

**Comment by andscoop** [comment]
@schnie I broke the files out into `/airflow/include`. I originally planned to put them into `/include/` but this would have potentially conflicted with the `/include/` dir we create on `astro airflow init` if a developer is working from root astro directory.

**Pull request merged**
